FROM golang:1.13.0

# RUN apk update \
#   && apk add --no-cache git curl make gcc g++ \
#   && go get github.com/oxequa/realize

WORKDIR /panenga-api

ENV GO111MODULE=on

COPY go.mod .
COPY go.sum .

RUN go mod download
COPY . .

# RUN GOOS=linux GOARCH=amd64 go build -o /main

ENV PORT=${PORT}
# ENTRYPOINT ["/main"]