CREATE DATABASE IF NOT EXISTS app_data;

USE app_data;

CREATE TABLE panels(
  id              INTEGER PRIMARY KEY AUTO_INCREMENT,
  title           VARCHAR(32) NOT NULL,
  panel_image     VARCHAR(255) NOT NULL UNIQUE,
  created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);